name: Publish to GH Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # New: tame npm networking + retries (helps avoid 429)
      - name: Configure npm for CI
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set registry https://registry.npmjs.org
          npm config set fund false
          npm config set audit false

      - name: Install dependencies (429-friendly)
        run: npm ci --prefer-offline --no-audit --no-fund --network-concurrency=1

      - name: Cache Puppeteer browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            puppeteer-${{ runner.os }}-

      #- name: Install Chromium for Puppeteer (r1022525)
        #run: npx puppeteer browsers install chromium@1022525

      - name: Install Chromium for Puppeteer (r1022525)
        run: npx --yes @puppeteer/browsers install chromium@1022525

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: dist
