name: Publish to GH Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # New: tame npm networking + retries (helps avoid 429)
      - name: Configure npm for CI
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set registry https://registry.npmjs.org
          npm config set fund false
          npm config set audit false

      - name: Install dependencies (429-friendly)
        run: npm ci --prefer-offline --no-audit --no-fund --network-concurrency=1

      # - name: Cache Puppeteer browsers
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/puppeteer
      #     key: puppeteer-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       puppeteer-${{ runner.os }}-

      # #- name: Install Chromium for Puppeteer (r1022525)
      #   #run: npx puppeteer browsers install chromium@1022525

      # - name: Install Chrome r1022525 for Puppeteer
      #   run: npx --yes @puppeteer/browsers install chrome@1022525

      # - name: Point Puppeteer at the installed Chrome
      #   shell: bash
      #   run: |
      #     set -euxo pipefail
      #     # Find the Chrome/Chromium executable that was just installed by @puppeteer/browsers
      #     BIN="$(ls -d $HOME/.cache/puppeteer/chrome/mac-*/1022525/chrome-*/Chrom*.app/Contents/MacOS/Chrom* | head -n1)"
      #     echo "Resolved Chrome binary: $BIN"
      #     test -x "$BIN"
      #     echo "PUPPETEER_EXECUTABLE_PATH=$BIN" >> "$GITHUB_ENV"

      # # Optional sanity check (helps catch path issues fast)
      # - name: Smoke-test Puppeteer launch
      #   run: node -e "const p=require('puppeteer');(async()=>{const b=await p.launch({executablePath:process.env.PUPPETEER_EXECUTABLE_PATH,headless:true});const pg=await b.newPage();await pg.goto('https://example.com',{waitUntil:'load',timeout:30000});console.log('PPT OK');await b.close();})();"

      - name: Build
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ env.PUPPETEER_EXECUTABLE_PATH }}
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: dist
